version: '3.8'

services:
  support-db:
    image: mysql:8.0
    container_name: support-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: support_db
    ports:
      - "3306:3306"
    volumes:
      - support_db_data:/var/lib/mysql

  support-service:
    build: .
    container_name: support-microservice
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://support-db:3306/support_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - support-db

volumes:
  support_db_data: