server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, health, info

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_URI:http://localhost:8081}
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1

            - id: envio-service
              uri: ${ENVIO_URI:http://localhost:8082}
              predicates:
                - Path=/api/shipments/**
              filters:
                - StripPrefix=1

            - id: inventario
              uri: ${INVENTARIO_URI:http://localhost:8083}
              predicates:
                - Path=/api/productos/**
              filters:
                - StripPrefix=1
            
            - id: pago-service
              uri: ${PAGO_URI:http://localhost:8084}
              predicates:
                - Path=/api/payments/**
              filters:
                - StripPrefix=1

            - id: pedidos-service
              uri: ${PEDIDOS_URI:http://localhost:8085}
              predicates:
                - Path=/api/pedidos/**
              filters:
                - StripPrefix=1

            - id: carrito
              uri: ${CARRITO_URI:http://localhost:8086}
              predicates:
                - Path=/api/carrito/**
              filters:
                - StripPrefix=1

            - id: notificaciones-service
              uri: ${NOTIFICACIONES_URI:http://localhost:8087}
              predicates:
                - Path=/api/notificaciones/**
              filters:
                - StripPrefix=1

            - id: support-service
              uri: ${SUPPORT_URI:http://localhost:8088}
              predicates:
                - Path=/api/support/**
              filters:
                - StripPrefix=1

            - id: resenas-service
              uri: ${RESENAS_URI:http://localhost:8089}
              predicates:
                - Path=/api/resenas/**
              filters:
                - StripPrefix=1
                
            - id: catalogo-service
              uri: ${CATALOGO_URI:http://localhost:8090}
              predicates:
                - Path=/api/catalogo/**
              filters:
                - StripPrefix=1

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false