spring.application.name=catalogo-service
server.port=8090

inventario.url=http://inventario:8083/productos
resenas.url=http://resenas-service:8089/resenas

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html