spring.application.name=notificaciones
server.port=8085

# Conector de Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Desactivar base de datos y migraciones (este servicio no usa tablas)
spring.liquibase.enabled=false
spring.jpa.hibernate.ddl-auto=none
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Credenciales genéricas para saltarnos la pantalla de bloqueo de Spring Security
spring.security.user.name=admin
spring.security.user.password=admin

# CONFIGURACIÓN DEL SERVIDOR DE CORREOS (Mailtrap simulado)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=api
spring.mail.password=645c4feae342b68cb62917990d7244ae
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false